### ISSUE TITLE
REPL wrap-up?

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#119]
import wrappers be gone? https://github.com/adriaanm/scala/tree/repl-wrappers

**Comment by adriaanm** [comment]
tentative for m5... very tentative

**Comment by som-snytt** [comment]
I thought you were going to say rewrite.

**Comment by SethTisue** [comment]
@adriaanm I assume you're done with this for 2.13.0(-RC1)

**Comment by som-snytt** [comment]
Time flies. What year is this? It's on my list to get back to magic contexts for REPL. I haven't looked at this branch yet, but I had one previously. I'll try to get something together on top of the jline3 branch. I would prefer REPL lines to wrap as function bodies, invoked with args from history on evaluation instead of statically linked by imports. That makes scripting more reasonable and garbage collecting results simpler. The other issue is calculating/minimizing imports. I haven't actually made a list of these items except until now. I've got day work, but Monday is a holiday.

**Comment by dwijnand** [comment]
Is this fixed with https://github.com/scala/scala/pull/8576 (2.12.x) / https://github.com/scala/scala/pull/8600 (2.13.x), i.e. `-Yrepl-use-magic-imports`?  If not, what are outcomes are we tracking with this?

**Comment by som-snytt** [comment]
I changed the title to more accurately reflect the scope.

The scope creep is at https://github.com/scala/scala-dev/issues/325

I didn't intend to call Adriaan "the scope creep".

I wish I had thought of https://github.com/scala/scala/pull/8633 earlier, which just tracks itself.
