### ISSUE TITLE
repl: jline code completer prints '\n' as "^J"

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#240]
To reproduce, type a long definition in the repl, end it with `// print` and hit `<tab>`

In `scala.tools.nsc.interpreter.PresentationCompilerCompleter.complete.print`, we do

```
      val printed = showCode(tree) + " // : " + tree.tpe.safeToString
      Candidates(cursor, "" :: printed :: Nil)
```

any embedded `\n' in`printed`will be printed as`^J`in the console by jline. If you do`Candidates(cursor, "" :: printed.split('\n').toList)`, it's somewhat improved, but a full fix is needed.

/cc @eloots

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt/issues/2480

**Comment by adriaanm** [comment]
Thanks! Workaround: https://github.com/sbt/util/pull/39/files

**Comment by eloots** [comment]
Hey,

Not sure what solves what exactly. I tried sbt 0.13.12 with scala 2.12 RC2 and the problem is still there.

[ericloots@Eric-Loots-MBP] $ more project/build.properties
sbt.version=0.13.12
/scb/Scala_2.12
[ericloots@Eric-Loots-MBP] $ sbt
[info] Loading global plugins from /Users/ericloots/.sbt/0.13/plugins
[info] Loading project definition from /Users/ericloots/Dropbox/Scala/ScalaCronosBlogs/Scala_2.12/project
[info] Set current project to scala_2-12 (in build file:/Users/ericloots/Dropbox/Scala/ScalaCronosBlogs/Scala_2.12/)

> console
> [info] Starting scala interpreter...
> [info]
> Welcome to Scala 2.12.0-RC2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_73).
> Type in expressions for evaluation. Or try :help.

scala> val l1 = List(1,2,3)
l1: List[Int] = List(1, 2, 3)

scala> val l2 = List(1,2,3)
l2: List[Int] = List(1, 2, 3)

scala> for { a <- l1; b <- l2; res = a + b } println(res) //print<TAB>

$line3.$read.$iw.$iw.l1.foreach[Unit](%28%28a: Int%29 => $line4.$read.$iw.$iw.l2.map[%28Int, Int%29, List[%28Int, Int%29]]%28%28%28b: Int%29 => {^J  val res = a.+%28b%29;^J  scala.Tuple2.apply[Int, Int]%28b, res%29^J}%29%29%28scala.collection.immutable.List.canBuildFrom[%28Int, Int%29]%29.foreach[Unit]%28%28%28x$1: %28Int, Int%29%29 => %28x$1: @scala.unchecked%29 match {^J  case scala.Tuple2%28%28b @ _%29, %28res @ _%29%29 => scala.Predef.println%28res%29^J}%29%29%29) // : Unit

Cheers, Eric

**Comment by adriaanm** [comment]
This was fixed by scala/scala#5450, which will go into 2.12.1

**Comment by SethTisue** [comment]
@eloots if you want to test it, you can use a recent 2.12.x nightly such as

```
resolvers += "nightlies" at "https://scala-ci.typesafe.com/artifactory/scala-release-temp/"
scalaVersion := "2.12.0-01b76a2-nightly"
```

**Comment by eloots** [comment]
@SethTisue: Thanks and verified that it indeed works.
