### ISSUE TITLE
Avoid inlining calls to sun.reflect.CallerSensitive annotated methods

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#33]
These are known to inspect the stack frame to lookup the calling class or method name.

**Comment by lrytz** [comment]
once this is implemented, test that it covers `MethodHandles.lookup`, https://docs.oracle.com/javase/8/docs/api/java/lang/invoke/MethodHandles.Lookup.html

**Comment by varming** [comment]
Will this issue be addressed in Scala 2.11 ? I am asking as sun.reflect.CallerSensitive was removed from JDK9, so this patch is needed to run 2.11 compiled code on JDK9.

**Comment by lrytz** [comment]
> sun.reflect.CallerSensitive was removed from JDK9

Do you have a reference for this? I'd like to read up.

We're not planning to fix this in 2.11.x (at this point), but I don't understand yet how it relates to the ability of running 2.11-compiled code on JDK 9, so I might be missing something important.

**Comment by varming** [comment]
My point was that sun.reflect.CallerSensitive has been removed in JDK9, so inlining of methods using sun.reflect.CallerSensitive could potentially cause problems when the JDK9 runtime cannot find the class. I noticed CallerSensitive in class files produced by scalac (it happens when an object extends Thread), and decided to investigate.

It turns out that missing runtime annotations are ignored by the class file parser (since java 1.5), so as long as sun.reflect.CallerSensitive is only used as an annotation, then there shouldn't be a problem. So I think everything is fine today, but inlining methods from the JDK is generally fishy as the JDK is tightly coupled to the JVM (minor version skew between the JDK and the JVM can break everything).

**Comment by adriaanm** [comment]
(hi Carsten!)

**Comment by lrytz** [comment]
thanks for the clarification! this is something to point out in the release notes. when inlining from a jar, users need to make sure to use the versions at runtime.

we are working on providing much more fine-grained compiler options that will allow people to specify where to inline from, see https://github.com/scala/scala-dev/issues/148. thanks for pointing out that we also need to take the JDK version into this mix.
