### ISSUE TITLE
JIRA not redirecting to new bug tracker?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#372]
e.g. at https://github.com/scalatest/scalatest/pull/1044 I clicked on the link to SI-8110 but I didn't land on scala/bug#8110, I landed on JIRA with a thud

I know we intended to do the redirect, not sure if it just hasn't happened yet, or we thought it happened but it isn't working

**Comment by adriaanm** [comment]
I haven't had a chance to ask Fabien about this.

**Comment by SethTisue** [comment]
For now, I at least updated the front matter at https://issues.scala-lang.org/secure/Dashboard.jspa to be more informative about the migration. (It had still said scala-dev and didn't say how to find migrated tickets.)

I want to also change the "Please use our new official issue tracker. This JIRA instance will be preserved as an archive only." to link to just scala/bug instead of scala/bug/issues, in the hopes that people will read the README before reporting an issue. But I can't find the setting. Do you remember where it is?

**Comment by adriaanm** [comment]
Done via https://issues.scala-lang.org/secure/admin/EditAnnouncementBanner!default.jspa

**Comment by ashawley** [comment]
I'm glad a redirect isn't enabled, yet.  I wanted to see if any of my watched tickets in Jira were worth subscribing to on Github.  Maybe add a note to a the dashboard that watched issues weren't exported?  Get them before it's too late.  Though maybe not a lot of people used it?

**Comment by adriaanm** [comment]
Not to worry! The original JIRA will remain available for the foreseeable
future as an archive

**Comment by adriaanm** [comment]
(Even with the redirect in place there will be a way to not get redirected )

**Comment by som-snytt** [comment]
Yet JIRA is a master of misdirection. That why it seems to work like magic.

To echo @ashawley I miss my list of "issues that interest me". I didn't like that JIRA subscribed me every time I chimed in with a stupid pun, but it was helpful to have a list of things I forgot I even cared about.

**Comment by retronym** [comment]
[Searching for "is:issue user:scala involves:som-snytt"](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Ascala+involves%3Asom-snytt) in the issues dashboard appears at least to find the puns. I don't [believe](https://stackoverflow.com/a/33478315/160378) that just subscribing or reacting to an issue is considered to be "involved" though.

**Comment by som-snytt** [comment]
It turns out it was puns all the way down.

**Comment by SethTisue** [comment]
@fsalvi is this something you might be interested in tackling? I still see people linking to the old JIRA tickets, and they still show up in Google searches.

and/or, how about removing the old JIRA from search engines, so people's searches take them to scala/bug instead? that's an easy-ish change, I think?

**Comment by fsalvi** [comment]
Yes, it looks reasonable to me.
I modified robots.txt to exclude the website from search engines.

**Comment by SethTisue** [comment]
awesome, thanks Fabien!

what about having the JIRA tickets redirect (automatically, or just by providing a link) to the corresponding scala/bug ticket...? is that too ambitious?

**Comment by SethTisue** [comment]
also, note to self: at the moment a Google Search such as
https://www.google.com/search?client=safari&rls=en&q=SI-907&ie=UTF-8&oe=UTF-8 still finds a JIRA ticket. it's probably just that Google hasn't noticed the robots.txt change yet, but we should check on it again in a month or so

**Comment by fsalvi** [comment]
Yes, I saw that.

Reading the google help, I found that:

If I block Google from crawling a page using a robots.txt disallow directive, will it disappear from search results?

Blocking Google from crawling a page is likely to decrease that page's ranking or cause it to drop out altogether over time. It may also reduce the amount of detail provided to users in the text below the search result. This is because without the page's content, the search engine has much less information to work with.

However, robots.txt Disallow does not guarantee that a page will not appear in results: Google may still decide, based on external information such as incoming links, that it is relevant. If you wish to explicitly block a page from being indexed, you should instead use the noindex robots meta tag or X-Robots-Tag HTTP header. In this case, you should not disallow the page in robots.txt, because the page must be crawled in order for the tag to be seen and obeyed.

And there's a link to the old issues page on every imported issue on github:
https://github.com/scala/bug/issues/907

I will try to find a better solution.
But, if everything is inside github, is it still useful to keep the old issues website ?

**Comment by adriaanm** [comment]
I don't think we need to keep the JIRA instance running anymore. For me, the ideal solution would be to  redirect `https://issues.scala-lang.org/browse/SI-(.*)` to `https://github.com/scala/bug/issues/(\1)` and  disable JIRA. Maybe we can archive the installation easily, just in case.

**Comment by fsalvi** [comment]
Ok, I added a redirect to the github issues. It's fine now.

**Comment by SethTisue** [comment]
sweeeeeeeeet, thanks Fabien!
