### ISSUE TITLE
2.12 regression: scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#457]
seen at e.g.:

* https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/6093/consoleFull
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/827/consoleFull

4 total failures, sample failure: `[error] Test scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest.simplifyJumpsInTryCatchFinally failed: scala.MatchError: List(Method(List(VarOp(ALOAD, 0), InvokeDynamic(INVOKEDYNAMIC, lambdaDeserialize, (Ljava/lang/invoke/SerializedLambda;)Ljava/lang/Object;, MethodHandle(6,scala/runtime/LambdaDeserialize,bootstrap,(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/invoke/MethodHandle;)Ljava/lang/invoke/CallSite;,false), List(MethodHandle(6,C,$anonfun$t$1,(III)I,false), MethodHandle(6,C,$anonfun$t$2,(II)I,false), MethodHandle(6,C,$anonfun$t$3$adapted,(Ljava/lang/String;)Ljava/lang/Object;,false))), Op(ARETURN)),List(),List()), Method(List(Label(0), LineNumber(8, Label(0)), Op(ICONST_3), Op(IRETURN), Label(4)),List(),List(LocalVariable(this,LC;,None,Label(0),Label(4),0)))) (of class scala.collection.immutable.$colon$colon), took 0.07 sec`

**Comment by hrhino** [comment]
This seems to be because the `perRunCache`  for `indyLambdaDeserializeMethods` is holding on to a `JavaClearable` rather than the cache itself, and that `WeakReference` is the only reference to the `JavaClearable` object... 

All of the method wrapping classes made by `BytecodeTesting` are named `C`, so if the GC cleans up that reference the cache will never get cleared, and we see stale data in it.

Sorry for the intrusion; long boring meeting at work and all..

**Comment by SethTisue** [comment]
scala/scala#6203, I suppose, then /cc @mkeskells @retronym

**Comment by hrhino** [comment]
I think this works:

```diff
@@ -46,8 +47,8 @@ abstract class BackendUtils extends PerRunInit {
    * inlining: when inlining an indyLambda instruction into a class, we need to make sure the class
    * has the method.
    */
-  private val indyLambdaImplMethods: ConcurrentHashMap[InternalName, mutable.LinkedHashSet[asm.Handle]] = recordPerRunJavaMapCache{
-    new ConcurrentHashMap[InternalName, mutable.LinkedHashSet[asm.Handle]]
+  private val indyLambdaImplMethods: ConcurrentHashMap[InternalName, mutable.LinkedHashSet[asm.Handle]] = recordPerRunCache {
+    new ConcurrentHashMap[InternalName, mutable.LinkedHashSet[asm.Handle]] with Clearable
   }
```

I don't _think_ the anon subclass will have negative implications, but I might be missing something.

**Comment by mkeskells** [comment]
@hrhino should be OK, and will prove the theory. I will work on a fix to the perRunLazy/JavaClearable to avoid this but it will not be for a few days, maybe a week due to my day job commitments and Scala Exchange, so best to go with something that works. Implications will not affect the common code flow IMO, and will still be faster that the path in 2.12.4. I presume that you will backport this fix to 2.11.x

I will also add some unit tests around perRunLazy and GC

**Comment by mkeskells** [comment]
added https://github.com/scala/scala/pull/6223
tests detect the problems as I see them locally, and added fixes appropriately

**Comment by SethTisue** [comment]
this is fixed, I believe? haven't seen it in a long time
