### ISSUE TITLE
Deprecation story for auto-tupling

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#496]
(to flesh out)

**Comment by eed3si9n** [comment]
Ref:
- Drop -Y flags that change language semantics https://github.com/scala/scala/pull/6505
- Spec doesn't mention automatic tupling https://github.com/scala/bug/issues/3583
- [Let's drop auto-tupling](https://contributors.scala-lang.org/t/lets-drop-auto-tupling/1799)
- Remove Two Warts: Auto-Tupling and Multi-Parameter Infix Operations https://github.com/lampepfl/dotty/pull/4311

**Comment by SethTisue** [comment]
@adriaanm is this something we need to make sure happens for RC1?

**Comment by adriaanm** [comment]
I think we can figure this (and any other deprecation strategy) out early in the 2.13.x cycle.

**Comment by Jasper-M** [comment]
I would just like to point out that once you have HList-like tuples in Scala 3, having auto-tupling only for arguments which have a `Tuple` upper bound is a pretty great way to have syntax-free arity abstraction. It seems a bit strange to on the one hand build arity abstraction into the language and std library, and on the other remove a feature that could make arity abstraction great, which *was* available when arity abstraction was hard to do anyway.

I don't think it could still cause confusion or weird runtime errors either, since auto-tupling will only happen when a tuple is already *expected*.

The reason that right now not much breaks between removing auto-tupling for `Any` or `Unit` bounded arguments, and removing it for everything, is probably that 
  - currently you have to use a bunch of Shapeless macros to convert between tuples and hlists,
  - currently tuples don't even share a common type, other than `Product` which *all* case classes have, and
  - no one in their right mind would write `def foo(a: (Int, Int))` or `def foo[A <: (Int, Int)](a: A)`, cause right now it's used exactly the same as `def foo(a: Int, b: Int)` except it has a bunch of extra overhead.

Without auto-tupling I think I would actually prefer (syntax-wise) shapeless hlists over built-in tuples-as-hlists. To me `foo((1, 2, 3))` looks worse/weirder/uglier than `foo(1 :: 2 :: 3 :: HNil)`.

**Comment by SethTisue** [comment]
new plan at https://github.com/lampepfl/dotty/pull/4311#issuecomment-435593905

**Comment by SethTisue** [comment]
Out of scope for Scala 2

**Comment by SethTisue** [comment]
Well, perhaps not out of scope. I just added some remarks at https://github.com/scala/bug/issues/3583#issuecomment-1484622220 . Let's leave this one closed and let discussion continue there.
