### ISSUE TITLE
Jenkins won't start new jobs

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#515]
go to https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/ and hit "Build with Parameters" followed by "Build", nothing happens.

things I have tried so far:

* logging out and back in
* weeping

possibly related, @hrhino's report at https://github.com/scala/scala/pull/6336 that Scabot apparently isn't able to kick off a Jenkins job either

**Comment by SethTisue** [comment]
Scabot/Jenkins are also turning up their noses and pretending not to see https://github.com/scala/scala/pull/6651, too. though for that PR, you can understand why Jenkins would feel that way.

**Comment by retronym** [comment]
Looks like the compiler-benchmark job artifacts have been hogging disk space, in particular, the scheduled jobs that collect profiles.


https://scala-ci.typesafe.com/log/all

```
Failed to write out the queue file /var/lib/jenkins/queue.xml
java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
```

I've manually changed that job definition to delete artifacts of jobs above a certain age, and changed the [run of `prof hot ...`](https://scala-ci.typesafe.com/benchq/benchmarks) to be weekly rather than nightly.

**Comment by retronym** [comment]
The `validate-main` jobs are now the biggest hog of disk space:

![image](https://user-images.githubusercontent.com/65551/40085711-b5c1e4f2-589b-11e8-83b2-8869d3bbaf42.png)

This might be exacerbated by the way we now archive JUnit XML files and the associated report. We should probably add a "delete old builds" rule to these builds, too.
