### ISSUE TITLE
Presentation Compiler Hackathon

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#56]
@SethTisue @retronym and @dragos went to Prague, and spent a few days hacking on the presentation compiler.

These are their stories.

**Comment by SethTisue** [comment]
> Last engineering meeting, we integrated the presentation compiler into the REPL and the Spark workbook. This work has since been polished and included in 2.12.0-M3 and the upcoming 2.11.8. In the process, the Scala IDE team has been able to close a number of tickets.
> 
> There are a couple residual issues that have been reported by Mirco, Iulian, and Simon Schaeffer recently, it would be good to take a look at these while they are in the same room, try to fix them, and help to share some presentation compiler knowledge around.
> 
> One fun feature that we could also try out is to integrate "hole driven development", which would drive autocompletion based on the expected type.

**Comment by retronym** [comment]
https://issues.scala-lang.org/browse/SI-9309

**Comment by SethTisue** [comment]
possible approaches:

* Jason and Iulian are suggesting adding a cache to

**Comment by SethTisue** [comment]
We're looking at fixing SI-9309 (red squiggles when directory structure doesn't match package structure). Jason has existing wip code for this in a branch (linked from the ticket).

Details:

We're trying to write a function from package name to a list of source files that define members of that package.

The existing code implements a heuristic for this function that takes the package name, translates it (once per source path element) to an expected source directory name (assuming exact correspondence between package structure and directory structure), and outline-parsing all source files in that directory.

Jason's initial efforts in his `ticket/9309` branch implement this function in a way that is guaranteed to succeed but is slow. In this naive approach, each compiler run begins by outline-compiling all known sources in the entire source path. That enters symbols for everything into the symbol table so all valid lookups will succeed. As a result, his one test case passes.

Possible next steps:
- testing:
  - write more test cases to make sure the fix is robust
  - test the fix in the actual context of ENSIME and/or ScalaIDE?
- performance:
  - assuming the fix is robust, we can improve performance as follows. The first time we need to look up an otherwise unknown symbol, we will then outline-parse all sources. But on subsequent queries, we will only re-parse files the IDE tells us have changed .
  - Jason and Iulian were also planning to implement a cache mapping source file names to lists of fully qualified names of top level ClassDefs/ModuleDefs, then invalidate cache entries for modified source files. (We're unsure whether this caching is actually needed; it could depend on whether it will work to just use the symbol table from a previous run as our cache.)

Seth is interested in perhaps instead, or to begin with, just tweaking the existing heuristic to look in directories at the right location _relative to the current source file_, instead of always computing the target location from the root of the source path entry. This would fix the common case (actually common, or only common for Seth?) where directory structure and package structure are in perfect correspondence _except for the omission of one or more top level directories_.

Open questions:
- Do we need the IDE to tell us which source files are modified or can we use existing API in the compiler for that?
- How do we handle source files that have gone away? (How does it work now?)

**Comment by dragos** [comment]
When sources go away the IDE just restarts the presentation compiler. IIRC there was a way to invalidate symbols and remove them from the symbol table, but unfortunately it was removed in 41507ba for sketchy reasons.

**Comment by SethTisue** [comment]
@dragos what if I don't delete a file, but just edit it and remove one or more of its top-level members? do you restart the presentation compiler in that case too (since the now no-longer-applicable symbol table entries can't be invalidated)?

**Comment by dragos** [comment]
No, it's different for files that are "loaded" in the presentation compiler (those that are type-checked together for each keystroke). In that case the type-checker can remove the old symbols at the "adaptToNewRun" step.

**Comment by SethTisue** [comment]
> In that case the type-checker can remove the old symbols at the "adaptToNewRun" step.

Iulian clarifies in person: this only works if the change to the file was actually made in the IDE. When the IDE runs the presentation compiler it always passes all source files that have open tabs, so the changed file gets included. But if the file were modified by some other means (e.g. by a git checkout or a different editor), then the IDE receives a notification that happens, and as a result, it restarts the presentation compiler.

**Comment by SethTisue** [comment]
> In that case the type-checker can remove the old symbols at the "adaptToNewRun" step.

Iulian clarifies in person: what happens may depend on whether the change to the file was actually made in the IDE. When the IDE runs the presentation compiler it always passes all source files that have open tabs, so normally changed files are included in that. But if the file was modified by some other means (e.g. by a git checkout or a different editor), then the IDE receives a notification that happens, and as a result, does it either 1) include the modified file in the next run even though it isn't open in the IDE, or 2) just restart the presentation compiler? Iulian isn't quite sure.

**Comment by SethTisue** [comment]
We're needing to modify how packages are created in the course of outline parsing.

Under normal circumstances (when directories and packages match), when the presentation compiler starts up, it scans the source path, sees what top-level subdirectories exist there, and makes packages corresponding to those directories. (Note that the subdirectories aren't eagerly recursed into; that will happen lazily if someone actually does something to look inside the package.)

Only later, during outline parsing, will the contents of the source files be processed. So by the time the outline parser sees e.g. `package a; object A` inside `a/A.scala`, seeing the enclosing directory already caused the creation of the package, so when we see `package a`, it refers to an already-known package.

But now consider the case where directories and packages don't match. For example if `A.scala` is at the root of the source tree, when we see `package a` we must add code that actually creates the package. (And of course, this just brings the outline parser in line with how the full compiler behaves.)

EDIT: implemented in https://github.com/retronym/scala/commit/ba5fc054ce58f6f226a5093a9d8f8cc896ef360f

**Comment by SethTisue** [comment]
https://github.com/retronym/scala/commit/1a9f32e9119ebda9d0e8ae9e5bd6abd69a59940a implements a strategy where we check the modification dates directly ourselves. It also shows how to write test code that does multiple compiler runs, changing source file contents and modification dates between runs.

**Comment by dragos** [comment]
I just reverse-engineered the IDE:
- for deleted files, it calls `askFilesDeleted`
- for changed files, it triggers an `askParsedEntered` and a re-typecheck of loaded files
- for modified packages or jars it restarts the compiler

**Comment by retronym** [comment]
`syncTopLevelSyms` also seems to be quite key to invalidating top level symbols that no longer exist in the source path. It is called from `parseAndEnter`

**Comment by SethTisue** [comment]
The altered test code in https://github.com/retronym/scala/commit/ba5fc054ce58f6f226a5093a9d8f8cc896ef360f where we use `askLoadedTyped` as suggested by @dragos has a (big) little bug; we need to wait for the response before proceeding, e.g. with `assert(response.get.isLeft)` or we'll never see any errors.

**Comment by SethTisue** [comment]
Our current approach where we outline-parse all sources up front is causing double-definition errors when the same source file that was already outline-parsed gets typechecked, resulting in e.g. "B is already defined as object B in package object b" (for `package b; object B`).

How to fix? We can't just outline-parse more lazily and exclude the file being typechecked from that batch of outline-parsing, because typechecking one file can trigger other files being typechecked as well.

Can we ask the presentation compiler to discard the results of outline-parsing on a particular file...?

**Comment by dragos** [comment]
Could this parse be done in a separate compiler Run?

**Comment by SethTisue** [comment]
attempting to run Jason's current code (5aabbc3c77e412e113d47bf333cfcc49e83d0f04) in ENSIME causes the following StackOverflowError when trying jump-to-definition on a symbol in a closed file in the wrong directory:

``` java
java.lang.StackOverflowError: null
    at scala.tools.nsc.Global.log(Global.scala:304) ~[scala-compiler-2.11.8-retreat3.jar:na]
    at scala.tools.nsc.Global.devWarning(Global.scala:294) ~[scala-compiler-2.11.8-retreat3.jar:na]
    at scala.tools.nsc.Global.devWarning(Global.scala:288) ~[scala-compiler-2.11.8-retreat3.jar:na]
    at scala.reflect.internal.Symbols$NoSymbol.owner(Symbols.scala:3542) ~[scala-reflect-2.11.8-retreat3.jar:na]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.model.Helpers$class.symbolIndexerName(Helpers.scala:110) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
    at org.ensime.core.RichPresentationCompiler.symbolIndexerName(RichPresentationCompiler.scala:198) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
```

Jason says it looks like the ENSIME code is getting NoSymbol back and is attempting to follow its owners chain — these days NoSymbol is its own owner, so you get a loop instead of our old friend the “NoSymbol does not have owner” error.

**Comment by SethTisue** [comment]
As mentioned on at least one of the Assembla tickets, a good minimum improvement would be to at least generate a warning when a mismatch between directory structure and package structure is found. New users may not be aware of the structure rule at all and thus be mystified when compilation fails and conclude ScalaIDE is simply poor quality, or, an experienced user may be know of the restriction but believe their code to be in compliance even when it isn't. (I don't know of any tool for detecting this problem; I don't think any of the popular linters do it.)

**Comment by SethTisue** [comment]
final state: Jason's branch was demoable in ScalaIDE on a project similar to the one in `t9309.scala` (with two source files). he tried a bigger project (an older rev of scalaz before the sources were re-orged, I think) that didn't work, but there wasn't time to investigate. so what we have so far is promising, but it's a ways from the finish line.

**Comment by fommil** [comment]
Nice! If anyone is in London out 14th Nov we could do something similar at Hack the Tower. It recurs monthly.

**Comment by fommil** [comment]
@rorygraves @aemoncannon @edani

**Comment by mkurz** [comment]
Any news here for fixing SI-9309?

**Comment by SethTisue** [comment]
sigh, afraid not. the meta-issue here, "Investment in Presentation Compiler", has been raised by the ENSIME folks for the next Scala Center Advisory Board meeting.

**Comment by SethTisue** [comment]
perhaps needless to say, it would be great if someone in the community wanted to pick this up. I did my best to write everything down here so that the progress we did make isn't lost.

**Comment by fommil** [comment]
We're happy to host a hackathon in London as part of the typelevel hack days. Myself and Rory are writing a presentation compiler testing library https://github.com/ensime/pcplod but as our advice to the committee says: this is too big for volunteers and I don't think we'll achieve anything except raising awareness.

**Comment by fommil** [comment]
Incidentally, what is the state of testing in the scala codebase itself? For a hack day to work, we'd need a stop by step guide (mostly borrowing from @milessabin's blog post) with an emphasis on pc testing.

As much as I'd love to see the pc in the repl in ensime, i honestly don't think anybody will step up to do it. It's a big piece of work. Instead, we're looking at displaying repl results inline in the code like cider does.

**Comment by fommil** [comment]
Btw @rorygraves and I are talking about related things at scala world, hence the testing library.

**Comment by milessabin** [comment]
@fommil many of the rough edges I mentioned in my post have been smoothed off now ... it's really a very pleasant experience. I need to write a followup post.

I'm happy to give you a run through on Saturday.

**Comment by fommil** [comment]
Yes, that would be good.

**Comment by som-snytt** [comment]
A link to further conversation would be appreciated, if it continues on gitter or a different project. Thx.

**Comment by fommil** [comment]
This open ticket seems to be from a long gone age and should now be closed.

**Comment by dwijnand** [comment]
Agreed, it doesn't seem to be usefully tracking any pending work.  We can always reopen it.
