### ISSUE TITLE
t6488 failing on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#566]
references:

* https://github.com/scala/bug/issues/6488
* https://github.com/scala/bug/issues/8406
* https://github.com/scala/scala/pull/7093#issuecomment-428001804
* https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/732/consoleFull

```
!! 1395 - run/t6488.scala                           [output differs][duration 10.37s]
% diff Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\t6488.check Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\t6488-run.log--- empty
+++ t6488-run.log
@@ -1,0 +1,1 @@
+Timed out waiting for process output!
##### Log file 'Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\t6488-run.log' from failed test #####

Timed out waiting for process output!
```

**Comment by som-snytt** [comment]
It looks like the junit test leaves an I/O thread behind, since the piping mechanism is no longer aborted.

The issue for t6488 is that it doesn't know the child process failed, since there's no exception and no way to test for it.

It might be nice to propagate the error state up, so that `exitValue` can re-throw the IOE with details.

The I/O thread is sitting at:
```
scala.sys.process.ProcessImpl$PipeSink.run(ProcessImpl.scala:208)
```

**Comment by som-snytt** [comment]
I see I mentioned the stale i/o thread on the PR https://github.com/scala/scala/pull/7093#issuecomment-414728313

The java 9 API `startPipeline` requires all processes started, and just throws.

**Comment by SethTisue** [comment]
has PR: https://github.com/scala/scala/pull/7362
