### ISSUE TITLE
To prepare for Java 9+ modularization, the standard library should not contain classes in scala.reflect

### ISSUE THREAD

**Issue by smarter** [scala/scala-dev#586]
Java modules do not allow split packages, that is having two modules on your modulepath containing packages with the same name (note that packages are not hierarchical in Java, so `scala` and `scala.reflect` are unrelated packages).
Unfortunately, the standard library contains a few classes in scala.reflect: https://github.com/scala/scala/tree/2.13.x/src/library/scala/reflect So we need to find a new home for them. Everything but ClassTag is basically obsolete ([although my attempt at getting rid of them wasn't successful](https://github.com/scala/scala/pull/6745)). So the main question is: where do we put `ClassTag` ? I think it's harmless enough that we could just put it in `scala` directly. WDYT ?

**Comment by dwijnand** [comment]
I had the same concern, but there's nothing in the `scala.reflect` package in `scala-reflect` so there's no split package: https://github.com/scala/scala/tree/2.13.x/src/reflect/scala/reflect

I'm not sure if it was intentional or not, and also it's a little confusing, but it looks like we dodged this particular bullet.
