### ISSUE TITLE
2.13 community build regressions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#652]
since recent Scala version bump (one of [these](https://github.com/scala/community-builds/commits/2.13.x/nightly.properties)),

* akka has a consistent test failure in `ByteStringSpec.scala`, see https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2577/artifact/logs/akka-build.log
* slick consistently fails to compile, infinite loop during compilation https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2578/artifact/logs/slick-build.log

both akka and slick block downstream projects, so fixes may uncover additional failures

**Comment by lrytz** [comment]
The akka failure is caused by https://github.com/scala/scala/pull/8311, the addition of `knownSize` to `BufferedIterator` allows calling `size` without consuming the iterator.

In 2.13.0:
```
scala> val it = Vector(1).iterator.buffered; it.size; it.toList
it: scala.collection.BufferedIterator[Int] = <iterator>
res0: List[Int] = List()
```

In current 2.13.x
```
scala> val it = Vector(1).iterator.buffered; it.size; it.toList
it: scala.collection.BufferedIterator[Int] = <iterator>
res0: List[Int] = List(1)
```

@szeiger I guess it's OK for size not to consume the iterator? cc @Jasper-M.

cc @patriknw, the test in question is
  - https://github.com/akka/akka/blob/0783855b2c85de1ab7b189785a4f6e640f56da53/akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala#L952
  - https://github.com/akka/akka/blob/0783855b2c85de1ab7b189785a4f6e640f56da53/akka-actor-tests/src/test/scala/akka/util/ByteStringSpec.scala#L166

**Comment by lrytz** [comment]
The slick failure is caused by https://github.com/scala/scala/pull/8272

**Comment by patriknw** [comment]
Thanks for letting us know. Shall we remove or change the test?
cc @raboof

**Comment by lrytz** [comment]
This would be enough to fix it: https://github.com/lrytz/akka/commit/8275b3810c54f21e051bef070a9c1a098756848a

**Comment by patriknw** [comment]
thanks, I can bring that back to akka/akka in your name

**Comment by lrytz** [comment]
I'll be famous!

**Comment by Jasper-M** [comment]
> @szeiger I guess it's OK for size not to consume the iterator? cc @Jasper-M.

The same is already true for other iterators which implement an efficient `knownSize`.  On 2.13.0:

```
scala> val it = Vector(1).iterator; it.size; it.toList
it: Iterator[Int] = <iterator>
res0: List[Int] = List(1)
```


Anyway, I think the rule is: don't use the iterator after calling `size`.  Because there's no guarantee that it is reusable. But there's also no guarantee that it isn't. Related issue: https://github.com/scala/bug/issues/11224

**Comment by lrytz** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2581/ is running with https://github.com/scala/scala/pull/8401 merged, so slick should pass.

**Comment by SethTisue** [comment]
green again
