### ISSUE TITLE
run new Vector through 2.13 community build

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#670]
testing https://github.com/scala/scala/pull/8534

cc @lrytz @szeiger

**Comment by szeiger** [comment]
The line number is a bit suspicious:
```
[scala-collection-laws] , scala.MatchError: 1 (of class java.lang.Integer)
[scala-collection-laws] scala.collection.immutable.VectorSliceBuilder.result(Vector.scala:1151)
```
The failing match must be the one in line 1152.

**Comment by szeiger** [comment]
Modifying `VectorTest.testSlice` to use sizes 0 to 100 yields:

```
[error] Test scala.collection.immutable.VectorTest.testSlice failed: java.lang.AssertionError: expected:<Range 36 until 66> but was:<Vector(36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 32, 33)>, took 0.465 sec
[error]     at scala.collection.immutable.VectorTest.$anonfun$testSlice$3(VectorTest.scala:345)
[error]     at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[error]     at scala.collection.immutable.VectorTest.$anonfun$testSlice$2(VectorTest.scala:341)
[error]     at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[error]     at scala.collection.immutable.VectorTest.$anonfun$testSlice$1(VectorTest.scala:340)
[error]     at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[error]     at scala.collection.immutable.VectorTest.testSlice(VectorTest.scala:336)
```

It's not an exception but probably the same bug. The exception is caused by a VectorSliceBuilder result having a maxDimension of 1 despite a size > 32. The bug is probably in rebalancing or earlier in keeping track of size of dimension during building.

**Comment by szeiger** [comment]
I updated the PR with a fix for a slicing bug (or two, depending on how you want to count them). Based on the nature of these bugs I'm not sure how they could lead to the MatchError. Can we do a new run of the special community build branch?

I used tested every possible slice of every Vector up to a length of 1000, including verifying the structure and comparing the results. I didn't enable it in the test suite by default because it takes several minutes to run.

If the MatchError persists I'll have to try to reproduce and simplify it in a different way. Slicing from a valid Vector should be absolutely solid now. My best guess at the moment is that an invalid Vector was produced by a bad slice and a consecutive slice ran into the other error mode.

**Comment by SethTisue** [comment]
> Can we do a new run of the special community build branch?

I'll do that tonight or tomorrow morning, but it takes a long time. You'd get a first round of feedback much faster by running scala-collections-laws yourself locally, outside of the community build.

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3234/

**Comment by SethTisue** [comment]
3234 fixed the failures. so likely we're good, but some other repos had intermittent failures, re-run queued to be sure: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/3235/

**Comment by szeiger** [comment]
https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/3239/ succeeded
