### ISSUE TITLE
spurious (and wrong) inliner warning with -Yopt:l:project

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#79]
given A.scala

```
final class A {
  @inline def f = 1
}
```

and B.scala

```
class B {
  def t(a: A) = a.f
}
```

Using `-Yopt:l:project` when yields a warning:

```
$ qsc A.scala
$ qsc -Yopt:l:project -cp . B.scala -Yopt-warnings
B.scala:2: warning: A::f()I is annotated @inline but cannot be inlined: the method is not final and may be overridden.
  def t(a: A) = a.f
                  ^
one warning found
```

**Comment by felixmulder** [comment]
This looks like fun to me. I take it that since `A` is final - the method `f` cannot be overwritten, thus the `callee.safeToInline` is incorrectly set to `false`.

**Comment by felixmulder** [comment]
This is the failing line:

``` scala
val canInlineFromSource =
  compilerSettings.YoptInlineGlobal ||
  calleeSource == CompilationUnit
// false
...

CallsiteInfo(
  safeToInline       =
    canInlineFromSource && //...
```

**Comment by felixmulder** [comment]
So since they're not part of the same source file and `YoptInlineGlobal` is not set - the inlining fails.

So to me it seems like the error message is incorrect. It should be something like

```
B.scala:2: warning: A::f()I is annotated @inline but cannot be inlined: YoptInlineGlobal is not set
  def t(a: A) = a.f
```

**EDIT:** so, I sort-of have a fix for this. Unfortunately I realised that `YoptInlineGlobal` is not the correct way to look at it. As the example states `-Yopt:l:project`  refers to inlining within the project. Not sure how to define this and there appears to be no code touching the `lProject` variable set in `ScalaSettings.scala`

**Comment by lrytz** [comment]
> the error message is incorrect

Yes indeed, that's what I meant to say; I agree the issue description is not entirely clear.

> inlining within the project. Not sure how to define this

It's defined as the set of classes being compiled in the current compiler run. This assumes a full compilation: in an incremental compilation, there would be no inlining from already-compiled classes of the same project.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/4966

**Comment by felixmulder** [comment]
Great :)
