### ISSUE TITLE
Clean up places where we use `@deprecated` + `@nowarn` where the latter would suffice

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#794]
I introduced one such into the codebase yesterday at https://github.com/scala/scala/pull/9785 because I'd forgotten about https://github.com/scala/scala/pull/9707. I can take it out again, but at the same time I should look around to see where else we used this pattern.

**Comment by SethTisue** [comment]
well I wasn't wrong that there was at least one other place, but I didn't find any more than that: https://github.com/scala/scala/pull/9788

**Comment by som-snytt** [comment]
I will miss the long-winded Q&A about adding deprecation to silence deprecations.

I'm sure I added some to tests at some point. That is, tests which necessarily invoke deprecated elements.

`-Xlint:suppression` to warn if deprecation was silenced by enclosing deprecation instead of (more explicit) nowarn?

**Comment by SethTisue** [comment]
> I'm sure I added some to tests at some point.

(I did see places where tests used `@deprecated` when `@nowarn` might have served just as well, but I focused on finding places where we had done the little dance involving using both of them.)
